#+AUTHOR: Sturm Mabie
#+CATEGORY:Posts
#+DATE:2020-08-09
#+MATHJAX:true
#+STARTUP:showeverything
#+TITLE:Implied Volatility of At-The-Money Options

Note: I want to thank Algoseek for providing historical SPY
option-chain data at a very reasonable price. Algoseek provides all
the market data you could possibly need, including equity, future,
option, forex, crypto data, and more! If you're interested in high
quality market data at low quality prices, check them out [[https://www.algoseek.com/][here]]!

Since the creation of the /Chicago Board Options Exchange/ (CBOE) in
1973, options have played an important part in financial markets,
allowing investors to hedge their portfolios against drawdowns, obtain
leverage while managing risk, and express nuanced investment
hypotheses. Options' asymmetric nature means that buying options
always comes with limited risk, a desirable property when compared to
shorting a stock or selling futures, both of which have unlimited
downside.

In this post we're going to talk about the mathematics of options, how
they are priced, and how to potentially profit off of them.

** Black-Scholes Model

   Before the advent of /Black-Scholes/ (BS), options were not traded
   on an exchange and instead they were bespoke contracts called
   warrants that were traded over-the-counter (OTC). Only when a
   reasonable model (BS) for pricing options was discovered did a
   market open for trading them, the CBOE. Options can be broadly
   split into two categories: American-style options, and
   European-style options. While European-style options can be traded
   in for the underlying only at expiration, American-style options
   can be exchanged for the underlying shares at any time.

   BS and its derivatives all concern themselves with European-style
   options as they are mathematically easier to work with, though as
   the name implies, are not very common in America. Even so, it's
   very rare for an investor to early exercise their American option,
   even when they have the right to do so. The reason for this is that
   an option's value can be decomposed into two parts: the intrinsic
   value of the option and the time value of the option. The more in
   the money an option is, the higher its intrinsic value, the longer
   the option has to maturity, the greater the option's time value. By
   choosing to exercise an option instead of merely selling it, an
   investor will generally make less money, as they are only capturing
   the intrinsic value of the option and missing out on the time
   value.

   Because of this, American options are rarely exercised early, and
   thus, BS should give us a relatively reasonable approximation, even
   if it's not a completely mathematically correct thing to do.

   The original Black-Scholes model has 6 principle inputs: the
   expected future volatility of the underlying asset, the current
   price of the underlying, the risk-free rate, the time to maturity,
   the strike price, and whether the option is a call or a put. Given
   these inputs, the model can generate a fair market price, or value,
   of the option. Unfortunately, unlike the other inputs, the expected
   future volatility of the underlying is unobservable and can only be
   estimated.

   Using Black-Scholes and a root finding algorithm (such as [[https://en.wikipedia.org/wiki/Brent%27s_method][Brent's method]]),
   we can also go the other way, finding the expected future
   volatility of the asset by using the current market price. This
   expected volatility is called the /implied volatility/, or simply
   IV. For an option to be fairly priced from a mathematical
   perspective, the option's IV should be equal to the realized
   volatility, which we can only observe after the option has
   expired. Let's consider /SPY/ (S&P 500 ETF) options that are
   at-the-money (ATM) and also have the shortest time to
   maturity. Below is a graph of the annualized IV of puts and calls
   vs the realized volatility over a 63-day rolling window:

   #+caption:IV vs RV
   [[file:/assets/iv.svg]]

   Note that because we're simply using a trailing window for the
   volatility calculation, this isn't an exact apples-to-apples
   comparison. Regardless, the results are interesting: the historical
   volatility is almost always lower than the IV for both puts and
   calls. From this chart, it's evident that options are rarely sold
   for a fair price, with a large premium on puts and a moderate
   premium on calls. And this is for close to or ATM options, which
   tend to have lower IVs than other options (see [[https://en.wikipedia.org/wiki/Volatility_smile][volatility smile]] for
   more information). This means that the further an option's strike
   price is from the current spot price, the more expensive it is
   compared to what Black-Scholes predicts. According to
   Black-Scholes, the IV of all options with the same time-to-maturity
   should have the same IV, regardless of strike price.

   Starting in around 2018, the IV of calls and puts are actually
   lower than the realized volatility, implying that options (both put
   and calls) are cheaper than their mathematical fair value. Also
   note that puts almost always command a premium over calls. This
   should come as no surprise: there are many more natural buyers of
   puts (predominantly investors looking for portfolio insurance) than
   buyers of calls (primarily speculators).

** Implied Volatility/Realized Volatility Arbitrage

   It's clear from the above graph of IVs that, most of the time, we
   are getting ripped off when buying options. So instead of buying
   options, we would want to sell them instead. Let's consider two
   simple strategies: one where we sell an ATM call everyday, and one
   where we sell an ATM put everyday. Below is a graph of the
   cumulative profit and loss of each strategy:

   #+caption:Call PnL vs Put PnL
   [[file:/assets/opnl.svg]]

   Surprisingly, even though puts have a higher IV on average, and
   thus command a higher price, we actually make more money selling
   calls than puts. We initially start making really good profits, but
   then things start to flatten out for both strategies, especially
   around 2018. Based on the IV graph we saw, this makes sense: we are
   selling options for below their fair mathematical value and losing
   money because of the positive difference between the realized
   volatility and IV.

   Even ignoring the regime change after 2018, selling calls and puts
   like this without a hedge in incredibly dangerous. Remember that
   unlike with buying options, selling options puts us in a situation
   in which we are taking virtually unlimited risk. If the volatility
   of the market spikes unexpectedly, we could very easily get into
   hot water: the amount of long-tail risk taken is so staggering as
   to make all but the riskiest investors run for the hills. With one
   bad day, not only could we be wiped out, but we could be on the
   hook for money we do not have.

** Hedging Risk

   In order to try and capture the option premiums while hedging away
   some our risk, we can hold the underlying ETF for the call
   strategy, and short the SPY ETF for the put strategy. While this
   hedges away the risk of large moves upward (downward) for the call
   (put) strategy, it still leaves us exposed to downward (upward)
   moves for the call (put) strategy. Unlike in the unhedged version
   where we sold a contract each day, we only sell one contract at a
   time to ensure that we are correctly hedged. When the option we
   sold matures, we buy the next available option that is closest to
   ATM, has the minimum maturity time, and has available bids. Note
   that we are not perfectly hedged because there will always be a
   small difference between the strike and spot price. Let's take a
   look at the return of both strategies:

   #+caption:Call Returns vs S&P 500
   [[file:/assets/callstrat.svg]]

   #+caption:Put Returns
   [[file:/assets/putstrat.svg]]

   The put strategy makes a marginal amount of return until 2018 when
   the IV of puts starts to trend lower than the actual realized
   volatility. Though we make money from the option premiums, it is
   barely enough to cover the persistent negative return from shorting
   the S&P 500 in good times and not enough in bad times, when the
   realized volatility outpaces the IV. The call strategy on the other
   hand does very well until 2018, improving upon the return of the
   S&P 500. Like with puts, we start to lose money after the start of
   2018 and finish slightly below the returns of the S&P 500 on
   2020-07-16. We do observe less of a drawdown when the market
   crashes though, as the premiums from the calls we write cushion the
   blows to a certain extent.

   In general, it's clear that even though puts are less fairly priced
   than calls, it's generally a better idea to write calls instead of
   puts. Hedging by longing the underlying doesn't have the large
   negative carry associated with hedging puts in bull markets and if
   the IV becomes unfavorable, one can simply stop selling calls
   (while still holding the underlying) and hold a pure beta portfolio
   until the historical realized volatility drops below the IV.

   However, if we tried to pause writing puts, we would still hold SPY
   short, costing us a lot of money in most market environments. We
   would be forced to unwind the hedge until the realized volatility
   drops. And even in favorable volatility environments, the premium
   from the puts was slight compared the cost of the short hedge, with
   only around a 15% return being realized from 2012 to 2018.

** Conclusion

   Perhaps the only take away we can honestly put forth is that
   options are difficult to profit off of, for both the buyers, and
   the sellers. In most market environments, the premium you are
   paying for portfolio insurance by buying puts is simply too large
   to be worth it. Even calls are overpriced, though not to such a
   large extent. But while buying options isn't the best idea, selling
   them comes with their own set of challenges, especially if you want
   to sell puts. If you forecast a low volatility environment of
   steady but marginal upward growth, selling covered calls, even ATM,
   can enhance your returns substantially; they also help mitigate
   losses during bear markets as well. The only situation in which
   selling ATM covered calls would not be appropriate would be if a
   strong bull market is forecasted: the premiums from the options are
   unlikely to be large enough to offset the money left on the table
   when capping the upside.

   Thanks for reading, hope you liked my first options post! I won't
   be sharing the code for this one as the option data isn't publicly
   available and without the data, the code doesn't have much
   value. If, however, you are interested in accessing the data, check
   out [[https://algoseek.com][Algoseek]] for all of your option data needs (and more!).
