#+AUTHOR: Sturm Mabie
#+CATEGORY:Posts
#+DATE:2020-08-14
#+MATHJAX:true
#+STARTUP:showeverything
#+TITLE:St. Petersburg Paradox, the Martingale, and Risk Management

Many financial practitioners have long been interested in gambling and
games of chance, from Ed Thorpe's, a former hedge fund manager,
seminal work on blackjack card counting [[https://www.amazon.com/Beat-Dealer-Winning-Strategy-Twenty-One/dp/0394703103][Beat the Dealer]], to the famous
hedge fund titan poker tournament (Take 'Em to School Poker
Tournament). The similarity is more than skin deep, with gambling
methods such as the [[https://en.wikipedia.org/wiki/Kelly_criterion][Kelly Criterion]] even making their way downtown to
investment strategy and risk management. In this post, we're going to
discuss the mathematics and implications for finance of two different
gambling related topics: the St. Petersburg Paradox and the Martingale
Strategy.

** St. Petersburg Paradox

   First proposed by Bernoulli, the St. Petersburg paradox is a simple
   game that illustrates how people's utility function differs from pure
   expected value theory. Given a fair coin, the coin is flipped until a
   heads does not appear and the player collects $2^n$ dollars where $n$
   is the number of heads. We can calculate the expected value easily by
   summing the probabilities and payoffs:

   $$E = \sum_{i=1}^\infty \frac{1}{2^i} 2^i = 1 + 1 + \cdots + 1 = \infty$$

   Even though the expected value in infinity, most people are willing to
   pay relatively little to play such a game, since it's unlikely that
   the player will win a large sum, and much more likely to not win any
   money or only make a moderate amount. The long tail of large potential
   profit forms a geometric distribution, a discrete distribution which
   models the likelihood of $n$ number of events happening in sequence:

   $$\text{P}(X = n) = q^{n-1}p$$

   Where $q = 1 - p$. Since we're using a fair coin, this simply becomes:

   $$\text{P}(X = n) = \left(\frac{1}{2}\right)^n$$

   The cumulative distribution function (CDF) is simply the chance
   that this doesn't happen:

   $$\text{P}(X \leq n) = 1 - \left(\frac{1}{2}\right)^n$$

   In order to make this a little more concrete, let's look at a graph of
   the likelihood and payoffs:

   #+caption:Payoff vs # Heads
   [[file:/assets/pwin.svg]]

   And a graph of the CDF:

   #+caption:Payoff vs # Heads
   [[file:/assets/pcdf.svg]]

   As we can see, the likelihood of receiving larger and larger
   payoffs becomes exponentially smaller, with 93.75% of the time the
   player getting 4 or less heads in a row, netting a maximum payoff
   of only $16.

   Now imagine that instead of only playing this game once, you could
   pay a certain amount and play over and over again until you lost
   all of your bankroll. How much would you be willing to pay now?
   Though probably not an infinite number of dollars, the value of the
   game has gone up significantly for you. Assuming you have an ample
   bankroll to weather the storm, over the long run you will profit
   handsomely: making small amounts occasionally interspersed with
   massive windfalls.

** The Martingale

   The Martingale Strategy is a popular betting strategy that has been
   used by centuries by gamblers. The idea is simple: every time you
   lose a bet, place a subsequent bet that is double the size so that
   you can make back your losses, plus one extra dollar. Assuming an
   infinite bankroll, the payoff will always be 1 dollar:

   $$2^n - (2^{n-1} + 2^{n-2} \cdots + 2^0) = 1$$


   $2^n$ represents your winnings, while the sum of $2^{n-1}$ to $2^0$
   are your losses up to that point. For example, let's use the simple
   example of betting on a fair coin. We have 3 dollars, so we can
   make a maximum of two bets of $1 and $2. The expected value looks
   like:

   $$ \text{E} = 0.5 (\$1) + 0.5 (0.5 (\$1) + 0.5 (-\$3)) = 0$$

   Even though the expected value is 0, the chance of losing $3 is
   only 25%, while the chance of winning $1 is 75%. In the general
   case, we need $2^{n-1}$ dollars to place $n$ bets, where the chance
   of winning $1 is:

   $$\text{P}(\$1) = 1 - \left(\frac{1}{2}\right)^n$$

   And losing:

   $$\text{P}(-\$(2^n-1)) = \left(\frac{1}{2}\right)^n$$

   Let's look at a graph of our chance of winning as a function of our
   bankroll:

   #+caption:Martingale
   [[file:/assets/mp.svg]]

   Much like the St. Petersburg Paradox, the Martingale exhibits a
   long-tail, except while the former has a long-tail of a windfall,
   the Martingale has a long-tail of absolute ruin. In general, if you
   want a $\left(\frac{1}{2}\right)^n$ chance of ruin, then you need
   $2^{n-1}$ dollars. So for example, to push your chance of losing it
   all to around one in a million, you would need about a million
   dollars to make that happen; and with such a large capital base, a
   one dollar profit in the best case isn't particularly appealing.

   The Martingale at first glance looks like a reasonable strategy,
   because the risk of ruin is pushed towards a very long, sometimes
   unobservable, tail -- which people have a hard time intuitively
   reasoning about. The low probability risk of losing it all is not
   correctly taken into account, much in the same way that the low
   probability of a massive windfall isn't taken into account for the
   intuitive fair value of the St. Petersburg Paradox.

** Application to Investing

   Imagine you were a manager of a trading desk, and one of your
   traders was offering the St. Petersburg Paradox to clients for a
   hefty fee while simultaneously Martingale betting on some
   derivative. You are unaware of what he's actually doing, but you
   can see the return stream from his trades. He's only been working a
   couple months and yet, he's minting money every day, though
   occasionally suffers some moderate to large losses. Based on his
   record, you might think that he's doing really well and that while
   his returns are moderately volatile, he generates a lot of profit,
   so that his risk-adjusted returns are pretty good.

   But you would be wrong, the trader is taking on massive levels of
   risk. But from your perspective of only looking at his return
   streams, this risk is non-existent, simply because the disastrous
   long-tail outcome has never been observed. When a distribution of
   returns exhibits a lot of excess kurtosis and skew, one needs to
   think very hard about how to appropriately manage risk. Popular
   risk models such as /Value at Risk/ (VaR) that estimate the worst
   95% or 99% outcome become insufficient when the return distribution
   deviates significantly from that of a log-normal distribution. If
   you used a 99% VaR model to measure the risk of your trader's
   strategies, it would fail to capture almost all of it, leaving you
   and your firm unknowingly exposed to existential extinction events.


** Conclusion

   While it's rare that any return stream is perfectly modeled by a
   log-normal distribution (most returns exhibit excess kurtosis and
   left-side skew), it's a good approximation for some, and completely
   unfit for others. Strategies such as selling volatility/variance
   insurance or selling far out-of-the-money calls or puts share many
   properties with the example of the aforementioned trader. It might
   look like superior risk-adjusted returns are being generated, but
   in fact this risk is just concentrated into a long-tail and thus
   unobservable until disaster strikes. This is often likened to
   "picking up pennies in front of a steam-roller"

   Thank for reading, I hope you enjoyed this post! It's a little
   different than usual, but a recent Matt Levine [[https://www.bloomberg.com/opinion/articles/2020-06-25/the-government-wants-esg-out-of-pensions][article]] about a
   Canadian pension fund blow-up (from taking long-tail risk) got me
   thinking about the similarities between St. Petersburg Paradox and
   the Martingale Strategy and long-tail risky strategies such as
   selling variance insurance. No code for this post, as only a couple
   of trivial graphs were made.
